# Generated by Django 4.2 on 2024-10-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
    ]
