# Generated by Django 4.2 on 2024-10-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': [('puede_aprobar', 'Puede aprobar registros'), ('puede_rechazar', 'Puede rechazar registros')], 'verbose_name_plural': 'Departamentos'},
        ),
    ]
